name: Test env

on:
  push:
    branches:
      - develop
      - main

concurrency: ${{ github.ref_name }}

jobs:
  job1:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo Secrets
        run: echo secret "${{secrets.SECRET_VAR }}" | sed 's/./& /g'
      - name: Echo Variables
        run: echo secret "${{vars.VARIABLE_VAR }}" | sed 's/./& /g'

  job2:
    runs-on: ubuntu-latest
#    environment:
#      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Echo Secrets
        run: echo secret "${{secrets.SECRET_VAR }}" | sed 's/./& /g'
      - name: Echo Variables
        run: echo secret "${{vars.VARIABLE_VAR }}" | sed 's/./& /g'
