name: Deploy API

on:
  push:
    branches:
      - develop
      - main

concurrency: ${{ github.ref_name }}

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Go environment
        uses: actions/setup-go@v4

      - name: Setup Node environment
        uses: actions/setup-node@v3
